//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Age_Brackets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Age_Brackets()
        {
            this.Experts_In_Categories = new HashSet<Experts_In_Categories>();
        }
    
        public int idAgeBracket { get; set; }
        public string nameAgeBracket { get; set; }
        public Nullable<int> fromAge { get; set; }
        public Nullable<int> toAge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experts_In_Categories> Experts_In_Categories { get; set; }
    }
}
