//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int idaAppointment { get; set; }
        public Nullable<System.DateTime> dateAppointment { get; set; }
        public Nullable<int> expertInDayId { get; set; }
        public Nullable<System.TimeSpan> startTimeAppointment { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.TimeSpan> endTimeAppointment { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ExpertInDay ExpertInDay { get; set; }
    }
}
