//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expert()
        {
            this.ExpertInDays = new HashSet<ExpertInDay>();
            this.Experts_In_Categories = new HashSet<Experts_In_Categories>();
        }
    
        public int idExpert { get; set; }
        public string firstNameExpert { get; set; }
        public string lastNameExpert { get; set; }
        public string tzExpert { get; set; }
        public string passwordExpert { get; set; }
        public string adressExpert { get; set; }
        public string phoneExpert { get; set; }
        public string mailExpert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertInDay> ExpertInDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experts_In_Categories> Experts_In_Categories { get; set; }
    }
}
